config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :users
  resources :tweets do
    member do
      get :heart
    end
  end
  resources :tweets do
    member do
      get :retweet
    end
  end
  resources :tweets do
    member do
      get :reply
    end
  end

  root 'tweets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/heart.rb
class Heart < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/retweet.rb
class Retweet < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :hearts
  has_many :retweets
  has_many :replies
  belongs_to :user

  validates :text, presence: true, length: { maximum: 140 }, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :tweets
  has_many :replies
  has_many :retweets
  has_many :hearts

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :new]

  # GET /tweets
  def index
    # # Code for user dropdown
    # # Also commented out code on tweet.js and application.html.haml
    # user = User.find_by(id: params["user"])

    search_text = params["text"]

    if search_text
      @tweets = Tweet.all.where("text like ?", "%#{search_text}%")
    # # More user dropdown code
    # elsif user
    #   @tweets = user.tweets
    else
      @tweets = Tweet.all.order("created_at DESC")
    end

  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # GET /heart_tweet_path
  def heart
    @tweet = Tweet.find(params[:id])
    if @tweet.hearts.where(user: current_user).count == 0
      @tweet.hearts.create(user: current_user)
      redirect_to tweets_url
    else
      redirect_to tweets_url, notice: "Hey, you already did that!"
    end

  end

  def retweet
    @tweet = Tweet.find(params[:id])
    if @tweet.retweets.where(user: current_user).count == 0
      @tweet.retweets.create(user: current_user)
      redirect_to tweets_url
    else
      redirect_to tweets_url, notice: "Hey, you already did that!"
    end

  end

  def reply
    @tweet = Tweet.find(params[:id])
    if @tweet.replies.where(user: current_user).count == 0
      @tweet.replies.create(user: current_user)
      redirect_to tweets_url
    else
      redirect_to tweets_url, notice: "Hey, you already did that!"
    end

  end

  # POST /tweets
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

    if @tweet.save
      redirect_to tweets_url, notice: 'Tweet was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tweets/1
  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private
  # Only allow a trusted parameter "white list" through.
  def tweet_params
    params.require(:tweet).permit(:text, :user_name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    user_id = params["user_id"]

    if user_id
      @tweets = Tweet.all.order("created_at DESC").where(user_id: user_id)
      split_name = @tweets[0].user.email.split("@")
      @user_name = split_name[0]
    # # More user dropdown code
    # elsif user
    #   @tweets = user.tweets
    else
      @tweets = Tweet.all.order("created_at DESC")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title
      = Minitwitter

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to tweets_path, class: "navbar-brand" do
            MiniTwitter!
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = link_to "Home", tweets_path
            %li
              = link_to new_tweet_path do
                New Tweet
            %li.navbar-text.toggle
              Search
            %li.search
              -# -# Code for user dropdown. Corresponding code commented out in tweet.js and tweets_controller.rb
              -# %form.navbar-form{action: tweets_path}
              -#   .formgroup
              -#     = select_tag "user", options_from_collection_for_select(User.all, "id", "email"), prompt: "User", class: "form-control"
              %form.navbar-form{:role => "search"}
                .input-group
                  %input.form-control{:id => "q", :name => "q", :placeholder => "Search Tweets", :type => "text"}/


          %ul.nav.navbar-nav.navbar-right
            -# %li
            -#   = link_to current_user.email
            - if user_signed_in?
              %p.navbar-text
                = current_user.email
              %li
                = link_to "Logout", destroy_user_session_path, method: :delete
            - else
              %li
                = link_to "Have an account? Log in", "/users/sign_in"
              %li
                = link_to "Don't have an account? Sign up", "/users/sign_up"
    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{type: "button", data: {dismiss: "alert"} }
            %span{aria: {hidden: "true"} } &times;
            %span.sr-only Close
          = msg
      = yield

app/views/tweets/_form.html.haml
= form_for @tweet, html: { class: "form-horizontal", role: "form" } do |f|
  -if @tweet.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:"

      %ul
        - @tweet.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :text, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :text, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/tweets/_tweet.html.haml
.media
  .media-left
    %a{:href => "#"}
      %img.media-object{:alt => "...", :src => "https://pbs.twimg.com/profile_images/489192650474414080/4RxZxsud_400x400.png", :height => "75px", :width => "75px"}/
  .media-body
    %h4.media-heading.top
      = tweet.text
      = link_to tweet.user.email, "/users/index?user_id=#{tweet.user.id}"
      •
      = distance_of_time_in_words_to_now(tweet.created_at)
    %p
      = tweet.text
    -# reserved space for tweet content
    -# %p
    -#   =
    %p
      = link_to reply_tweet_path(tweet) do
        %i.fa.fa-reply{"aria-hidden" => "true"}
      = tweet.replies.count

      = link_to retweet_tweet_path(tweet) do
        %i.fa.fa-retweet{"aria-hidden" => "true"}
      = tweet.retweets.count

      = link_to heart_tweet_path(tweet) do
        %i.fa.fa-heart{"aria-hidden" => "true"}
      = tweet.hearts.count

      = link_to "•••", tweet_path(tweet)

app/views/tweets/edit.html.haml
.page-header
  = link_to tweets_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @tweet, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing tweet

= render 'form'

app/views/tweets/index.js.erb
$('#tweet').html('<%= j(render @tweets) %>')

app/views/tweets/new.html.haml
.page-header
  = link_to tweets_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New tweet

= render 'form'

app/views/tweets/show.html.haml
.page-header
  = link_to tweets_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_tweet_path(@tweet), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show tweet

%dl.dl-horizontal
  %dt Text:
  %dd= @tweet.text
  %dt User name:
  %dd= @tweet.user.email

app/views/users/index.html.haml
.col-md-6
  %h1
    = @user_name.capitalize
  .container
    .container
      %h4
        email:
        = @tweets[0].user.email

.col-md-6
  %h3
    Recents:
  .container
    .table-responsive
      %table.table.table-striped.table-bordered.table-hover
        %tbody
          - @tweets.each_with_index do |tweet, index|
            %tr
              = render tweet